name: CI
on:
  push:
    branches:
      - main
  schedule:
    # Runs "everyday at 11 AM IST ( 5:30 UTC timezone)" (see https://crontab.guru)
    - cron: '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio:Headless
        - uses: actions/upload-artifact@v3
          with:
            name: allureReport
            path: ./reports/allure/allure-report