name: CI
on:
  push:
    branches:
      - main
  schedule:
    # Runs "everyday at 11 AM IST ( 5:30 UTC timezone)" (see https://crontab.guru)
    - cron: '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdioo
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs