name: CI
on:
  push:
    branches:
      - main
  schedule:
    # Runs "everyday at 11 AM IST ( 5:30 UTC timezone)" (see https://crontab.guru)
    - cron: '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio:Headless
        - uses: actions/upload-artifact@v3
          with:
            name: allureReport
            path: ./reports/allure/allure-report
        - name: Get Allure history
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages

        - name: Test marketplace action
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
            allure_results: build/allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history

        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history

        - name: Post the link to the report
          if: always()
          uses: Sibz/github-status-action@v1
          with: 
            authToken: ${{secrets.GITHUB_TOKEN}}
            context: 'Test report'
            state: 'success'
            sha: ${{ github.event.pull_request.head.sha || github.sha }}
            target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
